// Соответствие названий стран из Global Demonlist кодам ISO 3166-1 alpha-2.
//
// Составлено по всем 12726 игрокам лидерборда: в данных встречается
// 143 разных значения country. Старый COUNTRY_MAP из main.py знал
// только 31 из них, поэтому у многих игроков флаг не показывался.
//
// 'Unknown' в словарь намеренно не включён - это не страна, а признак
// того, что игрок её не указал. Таких 5088 из 12726, то есть 40%.

const COUNTRY_CODES: Record<string, string> = {
  'Afghanistan': 'af',
  'Albania': 'al',
  'Algeria': 'dz',
  'Andorra': 'ad',
  'Argentina': 'ar',
  'Armenia': 'am',
  'Aruba': 'aw',
  'Australia': 'au',
  'Austria': 'at',
  'Azerbaijan': 'az',
  'Bahrain': 'bh',
  'Bangladesh': 'bd',
  'Belarus': 'by',
  'Belgium': 'be',
  'Bolivia': 'bo',
  'Bosnia-and-Herzegovina': 'ba',
  'Brazil': 'br',
  'Bulgaria': 'bg',
  'Cambodia': 'kh',
  'Canada': 'ca',
  'Canary-Islands': 'es',
  'Cape-Verde': 'cv',
  'Chile': 'cl',
  'China': 'cn',
  'Colombia': 'co',
  'Costa-Rica': 'cr',
  'Croatia': 'hr',
  'Cuba': 'cu',
  'Cyprus': 'cy',
  'Czech-Republic': 'cz',
  'Denmark': 'dk',
  'Dominican-Republic': 'do',
  'Ecuador': 'ec',
  'Egypt': 'eg',
  'El-Salvador': 'sv',
  'England': 'gb',
  'Estonia': 'ee',
  'Finland': 'fi',
  'France': 'fr',
  'Gabon': 'ga',
  'Georgia': 'ge',
  'Germany': 'de',
  'Ghana': 'gh',
  'Gibraltar': 'gi',
  'Greece': 'gr',
  'Greenland': 'gl',
  'Guam': 'gu',
  'Guatemala': 'gt',
  'Guernsey': 'gg',
  'Guyana': 'gy',
  'Haiti': 'ht',
  'Honduras': 'hn',
  'Hong-Kong': 'hk',
  'Hungary': 'hu',
  'Iceland': 'is',
  'India': 'in',
  'Indonesia': 'id',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Ireland': 'ie',
  'Isle-of-Man': 'im',
  'Israel': 'il',
  'Italy': 'it',
  'Jamaica': 'jm',
  'Japan': 'jp',
  'Jordan': 'jo',
  'Kazakhstan': 'kz',
  'Kenya': 'ke',
  'Kosovo': 'xk',
  'Kuwait': 'kw',
  'Kyrgyzstan': 'kg',
  'Laos': 'la',
  'Latvia': 'lv',
  'Lebanon': 'lb',
  'Libya': 'ly',
  'Liechtenstein': 'li',
  'Lithuania': 'lt',
  'Luxembourg': 'lu',
  'Macedonia': 'mk',
  'Malaysia': 'my',
  'Maldives': 'mv',
  'Mali': 'ml',
  'Malta': 'mt',
  'Mexico': 'mx',
  'Moldova': 'md',
  'Mongolia': 'mn',
  'Montenegro': 'me',
  'Morocco': 'ma',
  'Myanmar': 'mm',
  'Netherlands': 'nl',
  'New-Zealand': 'nz',
  'Nicaragua': 'ni',
  'Nigeria': 'ng',
  'Norway': 'no',
  'Oman': 'om',
  'Pakistan': 'pk',
  'Palestine': 'ps',
  'Panama': 'pa',
  'Paraguay': 'py',
  'Peru': 'pe',
  'Philippines': 'ph',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Puerto-Rico': 'pr',
  'Qatar': 'qa',
  'Republic-of-the-Congo': 'cg',
  'Romania': 'ro',
  'Russia': 'ru',
  'Saint-Vincent-and-the-Grenadines': 'vc',
  'Saudi-Arabia': 'sa',
  'Scotland': 'gb',
  'Senegal': 'sn',
  'Serbia': 'rs',
  'Singapore': 'sg',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Somalia': 'so',
  'South-Africa': 'za',
  'South-Korea': 'kr',
  'Spain': 'es',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Syria': 'sy',
  'Taiwan': 'tw',
  'Tajikistan': 'tj',
  'Thailand': 'th',
  'Togo': 'tg',
  'Trinidad-and-Tobago': 'tt',
  'Tunisia': 'tn',
  'Turkey': 'tr',
  'Turkmenistan': 'tm',
  'Ukraine': 'ua',
  'United-Arab-Emirates': 'ae',
  'United-Kingdom': 'gb',
  'United-States': 'us',
  'Uruguay': 'uy',
  'Uzbekistan': 'uz',
  'Venezuela': 've',
  'Vietnam': 'vn',
  'Wales': 'gb',
  'Yemen': 'ye',
  'Zambia': 'zm',
};

/**
 * Название страны -> код ISO ('United-States' -> 'us').
 * Возвращает null, если страна неизвестна или не указана.
 */
export function countryCode(name: string): string | null {
  return COUNTRY_CODES[name] ?? null;
}
