// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ПРЯМОЕ подключение, без пулера.
    //
    // Этот файл читает только консоль Prisma (migrate, studio, generate).
    // Сайт подключается сам, через адаптер в src/lib/prisma.ts, и берёт
    // оттуда пулерную DATABASE_URL.
    //
    // Разделение нужно потому, что пулер не пропускает команды миграций:
    // он держит соединение в режиме, где CREATE TABLE и подобное ломается.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
